name: Periodic Model Calibration

on: 
  schedule:
    - cron: '0 0 * * *'  #minutes, hours, day, month, day of week 

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Generate and Store Timestamp
      run: |
        timestamp=$(date '+%Y%m%d%H%M%S')
        echo "$timestamp" > timestamp.txt
      id: timestamp 

    - name: Run Tests with Pytest
      run: |
        pip install pytest pytest-cov
        mkdir -p test-reports
        pytest test/tests.py \
            --maxfail=5 --disable-warnings -q \
            --junitxml=test-reports/results.xml \
            --cov=src --cov-report=term-missing

    - name: Check File Permissions
      run: |
        ls -l ./src/train_model.py

    - name: Set File Permissions
      run: |
        chmod +x ./src/train_model.py

    - name: Retrain Model
      run: |
        timestamp=$(cat timestamp.txt) # Use the timestamp in your training script
        python ./src/train_model.py --timestamp "$timestamp"

    - name: Evaluate Model and Log Metrics
      run: |
        timestamp=$(cat timestamp.txt) # Use the timestamp in your training script
        python ./src/evaluate_model.py  --timestamp "$timestamp"
        mkdir -p $GITHUB_WORKSPACE/metrics
        metrics_filename="metrics/${timestamp}_metrics.json"
        mv $metrics_filename $GITHUB_WORKSPACE/metrics/
      continue-on-error: false  # Continue even if evaluation fails

    - name: Store and Version the New Model
      run: |
        timestamp=$(cat timestamp.txt)
        mkdir -p $GITHUB_WORKSPACE/models
        model_filename="model_${timestamp}_dt_model.joblib"
        mv $model_filename $GITHUB_WORKSPACE/models/

    - name: Commit and Push Changes
      run: |
        git config --global user.email "gupta.saumy@northeastern.edu"
        git config --global user.name "SaumyaGupta-1907"
        git add $GITHUB_WORKSPACE/metrics/$metrics_filename $GITHUB_WORKSPACE/models/$model_filename
        git commit -m "Add metrics and updated model"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Verify artifacts
      run: |
        test -f "$GITHUB_WORKSPACE/metrics/$metrics_filename" || (echo "Metrics missing!" && exit 1)
        test -f "$GITHUB_WORKSPACE/models/$model_filename" || (echo "Model missing!" && exit 1)


